/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorLibroABM;
import Controlador.SoloLetrasONum;
import Modelo.EABM;
import Modelo.EPopupLibro;
import Modelo.EValidarCaracter;
import java.awt.Color;
import java.awt.Frame;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import javax.swing.JTextField;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author Usuario
 */
public class LibroABM extends javax.swing.JDialog {

    private EABM eabm;
    private int idUsuario;
    private ControladorLibroABM cLibroABM;
    private boolean estado;

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    
    
    
    public int getIdUsuario() {
        return idUsuario;
    }

    public EABM getEabm() {
        return eabm;
    }

    public JComboBox getComboAutor() {
        return comboAutor;
    }

    public JComboBox getComboEditorial() {
        return comboEditorial;
    }

    public JComboBox getComboGenero() {
        return comboGenero;
    }
    public JXDatePicker getjXDatePicker2() {
        return calendario;
    }

    public JTextField getTextCantidad() {
        return textCantidad;
    }

    public JTextField getTextNombre() {
        return textNombre;
    }

    public JTextField getTextPrecio() {
        return textPrecio;
    }

    public JXDatePicker getCalendario() {
        return calendario;
    }

    public JSlider getSliderValoracion() {
        return sliderValoracion;
    }

    public LibroABM(Frame frame, boolean bln, EABM eabm, int idUsuario) {
        super(frame, bln);

        this.eabm = eabm;
        this.idUsuario = idUsuario;
        this.setDefaultLookAndFeelDecorated(true);
        try {
            BufferedImage miImagen = ImageIO.read(getClass().getResource("/Imagen/Libro/Libro" + EABM.Alta + ".jpg"));
            this.setContentPane(new ImagenFondo(miImagen));
            initComponents();
            this.cLibroABM = new ControladorLibroABM(this);
            cLibroABM.CompletarCampos();
            calendario.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
            ConfigurarSlider();
  
            SoloLetrasONum soloNumeros = new SoloLetrasONum(this, EValidarCaracter.Numero);
            SoloLetrasONum soloFloat = new SoloLetrasONum(this, EValidarCaracter.Float);
            this.textCantidad.addKeyListener(soloNumeros);
            this.textPrecio.addKeyListener(soloFloat);
            
            
        } catch (IOException ex) {
            Logger.getLogger(LibroABM.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void ConfigurarSlider() {
        Hashtable labelTable = new Hashtable();
        int rojo=255;
        int verde=0;
        for (int i = 1; i <= this.sliderValoracion.getMaximum(); i++) {
            JLabel  etiqueta= new JLabel(new Integer(i).toString());
            etiqueta.setForeground(new Color(rojo,verde,0 ));
            rojo-=25;
            verde+=25;
            labelTable.put(new Integer(i), etiqueta);
        }
        this.sliderValoracion.setLabelTable(labelTable);
    }

    public LibroABM(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            BufferedImage miImagen = ImageIO.read(getClass().getResource("/Imagen/Libro/Libro" + EABM.Alta + ".jpg"));
            this.setContentPane(new ImagenFondo(miImagen));
            initComponents();
        } catch (IOException ex) {
            Logger.getLogger(LibroABM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRectTranslucido1 = new org.edisoncor.gui.panel.PanelRectTranslucido();
        jLabel6 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textPrecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textCantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboAutor = new javax.swing.JComboBox();
        comboEditorial = new javax.swing.JComboBox();
        comboGenero = new javax.swing.JComboBox();
        buttonAgregarAutor = new org.edisoncor.gui.button.ButtonIcon();
        buttonAgregarEditorial = new org.edisoncor.gui.button.ButtonIcon();
        buttonAgregarGenero = new org.edisoncor.gui.button.ButtonIcon();
        calendario = new org.jdesktop.swingx.JXDatePicker();
        jPanel1 = new javax.swing.JPanel();
        sliderValoracion = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        buttonAceptar = new org.edisoncor.gui.button.ButtonSeven();
        buttonCancelar = new org.edisoncor.gui.button.ButtonSeven();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelRectTranslucido1.setBackground(new java.awt.Color(204, 204, 0));
        panelRectTranslucido1.setColorDeBorde(new java.awt.Color(0, 204, 204));
        panelRectTranslucido1.setColorPrimario(new java.awt.Color(0, 102, 0));
        panelRectTranslucido1.setColorSecundario(new java.awt.Color(0, 204, 204));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Nombre:");
        jLabel6.setToolTipText("");

        textNombre.setText("asdas");
        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Cantidad:");

        textPrecio.setText("22");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Precio:");

        textCantidad.setText("12");
        textCantidad.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Valoracion:");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 204));
        jLabel10.setText("Fecha de publicacion:");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Autor:");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Editorial:");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("Genero:");

        buttonAgregarAutor.setBackground(new java.awt.Color(204, 204, 255));
        buttonAgregarAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Libro/add.png"))); // NOI18N
        buttonAgregarAutor.setText("buttonIcon1");
        buttonAgregarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarAutorActionPerformed(evt);
            }
        });

        buttonAgregarEditorial.setBackground(new java.awt.Color(204, 204, 255));
        buttonAgregarEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Libro/add.png"))); // NOI18N
        buttonAgregarEditorial.setText("buttonIcon1");
        buttonAgregarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarEditorialActionPerformed(evt);
            }
        });

        buttonAgregarGenero.setBackground(new java.awt.Color(204, 204, 255));
        buttonAgregarGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Libro/add.png"))); // NOI18N
        buttonAgregarGenero.setText("buttonIcon1");
        buttonAgregarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarGeneroActionPerformed(evt);
            }
        });

        calendario.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        sliderValoracion.setBackground(new java.awt.Color(102, 0, 102));
        sliderValoracion.setForeground(new java.awt.Color(204, 0, 204));
        sliderValoracion.setMaximum(10);
        sliderValoracion.setMinimum(1);
        sliderValoracion.setPaintLabels(true);
        sliderValoracion.setValue(0);
        sliderValoracion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sliderValoracion.setFocusable(false);
        sliderValoracion.setRequestFocusEnabled(false);
        sliderValoracion.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sliderValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sliderValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panelRectTranslucido1Layout = new javax.swing.GroupLayout(panelRectTranslucido1);
        panelRectTranslucido1.setLayout(panelRectTranslucido1Layout);
        panelRectTranslucido1Layout.setHorizontalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido1Layout.createSequentialGroup()
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)))))
                    .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(23, 23, 23)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textNombre)
                        .addComponent(calendario, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                            .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboAutor, 0, 130, Short.MAX_VALUE)
                                .addComponent(comboEditorial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buttonAgregarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(buttonAgregarGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(buttonAgregarEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addComponent(textCantidad))
                    .addComponent(textPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRectTranslucido1Layout.setVerticalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9))
                    .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAgregarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAgregarEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAgregarGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe WP", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LIBRO");

        buttonAceptar.setBackground(new java.awt.Color(255, 204, 0));
        buttonAceptar.setForeground(new java.awt.Color(204, 255, 255));
        buttonAceptar.setText("Aceptar");
        buttonAceptar.setColorBrillo(new java.awt.Color(255, 255, 204));
        buttonAceptar.setColorDeSombra(new java.awt.Color(51, 51, 51));
        buttonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceptarActionPerformed(evt);
            }
        });

        buttonCancelar.setBackground(new java.awt.Color(255, 204, 0));
        buttonCancelar.setForeground(new java.awt.Color(204, 255, 255));
        buttonCancelar.setText("Cancelar");
        buttonCancelar.setColorBrillo(new java.awt.Color(255, 255, 204));
        buttonCancelar.setColorDeSombra(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreActionPerformed

    private void buttonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAceptarActionPerformed
    
        
       if( this.cLibroABM.GestionarAceptar()){
            this.setVisible(false);
       }
       
       
       
    }//GEN-LAST:event_buttonAceptarActionPerformed

    private void buttonAgregarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarAutorActionPerformed
       this.cLibroABM.GenerarAgregarColaboradores(EPopupLibro.Autor);
    }//GEN-LAST:event_buttonAgregarAutorActionPerformed

    private void buttonAgregarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarEditorialActionPerformed
       this.cLibroABM.GenerarAgregarColaboradores(EPopupLibro.Editorial);
    }//GEN-LAST:event_buttonAgregarEditorialActionPerformed

    private void buttonAgregarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarGeneroActionPerformed
      this.cLibroABM.GenerarAgregarColaboradores(EPopupLibro.Genero);
    }//GEN-LAST:event_buttonAgregarGeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibroABM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibroABM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibroABM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibroABM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LibroABM dialog = new LibroABM(new javax.swing.JFrame(), true, EABM.Modificacion, -1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonSeven buttonAceptar;
    private org.edisoncor.gui.button.ButtonIcon buttonAgregarAutor;
    private org.edisoncor.gui.button.ButtonIcon buttonAgregarEditorial;
    private org.edisoncor.gui.button.ButtonIcon buttonAgregarGenero;
    private org.edisoncor.gui.button.ButtonSeven buttonCancelar;
    private org.jdesktop.swingx.JXDatePicker calendario;
    private javax.swing.JComboBox comboAutor;
    private javax.swing.JComboBox comboEditorial;
    private javax.swing.JComboBox comboGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.panel.PanelRectTranslucido panelRectTranslucido1;
    private javax.swing.JSlider sliderValoracion;
    private javax.swing.JTextField textCantidad;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPrecio;
    // End of variables declaration//GEN-END:variables
}
