/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Cliente;
import Modelo.EABM;
import Modelo.Usuario;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.IOException;
import static java.lang.System.in;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {

    private Cliente cliente;
    private Usuario user;

    /**
     * Creates new form Menu
     */
    public Menu(Usuario user) {

        try {
            this.user=user;
            
            //this.cliente = cliente;
            BufferedImage miImagen = ImageIO.read(getClass().getResource("/Imagen/Menu/fondoMenu.jpg"));
            this.setContentPane(new ImagenFondo(miImagen));
            initComponents();
            this.etiquetaFecha.setText(this.etiquetaFecha.getText() + this.user.getFechaDeRegistro());
            RestringirAccesso();
            this.setResizable(false);
            // this.itemCliente.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void RestringirAccesso() {
        switch (user.getRango()) {
            case Administrador:
                this.itemLibro.setVisible(false);
                this.itemCliente.setVisible(false);
                break;
            case Empleado:
                this.itemEmpleado.setVisible(false);
                this.itemLibro.setVisible(false);
                this.itemCliente.setVisible(false);
                break;
            case Cliente:
                this.itemAdminLibro.setVisible(false);
                this.itemEmpleado.setVisible(false);
                this.itemInformacion.setVisible(false);
                break;
            default:
                throw new AssertionError(user.getRango().name());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        etiquetaUsuario = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaApellido = new javax.swing.JLabel();
        etiquetaFecha = new javax.swing.JLabel();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        jMenuBar3 = new javax.swing.JMenuBar();
        itemLibro = new javax.swing.JMenu();
        itemCompraAlquiler = new javax.swing.JMenuItem();
        itemMisLibros = new javax.swing.JMenuItem();
        itemCliente = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        itemAdminLibro = new javax.swing.JMenu();
        buttonLibroAlta = new javax.swing.JMenuItem();
        buttonLibroModificar = new javax.swing.JMenuItem();
        buttonLibroBaja = new javax.swing.JMenuItem();
        buttonLibroMostrar = new javax.swing.JMenuItem();
        itemEmpleado = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        itemInformacion = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("asdas");

        etiquetaUsuario.setFont(new java.awt.Font("Minerva", 3, 24)); // NOI18N
        etiquetaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaUsuario.setText("Usuario:");

        etiquetaNombre.setFont(new java.awt.Font("Minerva", 3, 24)); // NOI18N
        etiquetaNombre.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaNombre.setText("Nombre:");

        etiquetaApellido.setFont(new java.awt.Font("Minerva", 3, 24)); // NOI18N
        etiquetaApellido.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaApellido.setText("Apellido:");

        etiquetaFecha.setFont(new java.awt.Font("Minerva", 3, 24)); // NOI18N
        etiquetaFecha.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaFecha.setText("Fecha de registro:");

        labelMetric1.setBackground(new java.awt.Color(255, 0, 51));
        labelMetric1.setForeground(new java.awt.Color(153, 255, 51));
        labelMetric1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric1.setText("BIENVENIDO");
        labelMetric1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        jMenuBar3.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jMenuBar3.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N

        itemLibro.setBackground(new java.awt.Color(153, 153, 153));
        itemLibro.setForeground(new java.awt.Color(0, 255, 255));
        itemLibro.setText("Libro");
        itemLibro.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N

        itemCompraAlquiler.setBackground(new java.awt.Color(153, 153, 153));
        itemCompraAlquiler.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        itemCompraAlquiler.setForeground(new java.awt.Color(51, 102, 255));
        itemCompraAlquiler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Menu/iconLibro.png"))); // NOI18N
        itemCompraAlquiler.setText("Comprar o alquilar");
        itemCompraAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCompraAlquilerActionPerformed(evt);
            }
        });
        itemLibro.add(itemCompraAlquiler);

        itemMisLibros.setBackground(new java.awt.Color(153, 153, 153));
        itemMisLibros.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        itemMisLibros.setForeground(new java.awt.Color(51, 102, 255));
        itemMisLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Menu/iconLibros.png"))); // NOI18N
        itemMisLibros.setText("Mis libros");
        itemLibro.add(itemMisLibros);

        jMenuBar3.add(itemLibro);

        itemCliente.setForeground(new java.awt.Color(51, 255, 255));
        itemCliente.setText("Cliente");
        itemCliente.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N

        jMenuItem1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuItem1.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Menu/iconDataUser.png"))); // NOI18N
        jMenuItem1.setText("Informacion");
        itemCliente.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(153, 153, 153));
        jMenuItem2.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Menu/iconLibroUser.png"))); // NOI18N
        jMenuItem2.setText("Libros");
        itemCliente.add(jMenuItem2);

        jMenuBar3.add(itemCliente);

        itemAdminLibro.setForeground(new java.awt.Color(255, 255, 204));
        itemAdminLibro.setText("Libro");
        itemAdminLibro.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N

        buttonLibroAlta.setBackground(new java.awt.Color(153, 153, 153));
        buttonLibroAlta.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        buttonLibroAlta.setForeground(new java.awt.Color(0, 51, 255));
        buttonLibroAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Menu/iconAltaLibro.png"))); // NOI18N
        buttonLibroAlta.setText("Alta");
        buttonLibroAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLibroAltaActionPerformed(evt);
            }
        });
        itemAdminLibro.add(buttonLibroAlta);

        buttonLibroModificar.setBackground(new java.awt.Color(153, 153, 153));
        buttonLibroModificar.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        buttonLibroModificar.setForeground(new java.awt.Color(0, 51, 255));
        buttonLibroModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Menu/iconModificarLibro.png"))); // NOI18N
        buttonLibroModificar.setText("Modficar");
        buttonLibroModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLibroModificarActionPerformed(evt);
            }
        });
        itemAdminLibro.add(buttonLibroModificar);

        buttonLibroBaja.setBackground(new java.awt.Color(153, 153, 153));
        buttonLibroBaja.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        buttonLibroBaja.setForeground(new java.awt.Color(0, 51, 255));
        buttonLibroBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Menu/iconBorrarLibro.png"))); // NOI18N
        buttonLibroBaja.setText("Baja");
        buttonLibroBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLibroBajaActionPerformed(evt);
            }
        });
        itemAdminLibro.add(buttonLibroBaja);

        buttonLibroMostrar.setBackground(new java.awt.Color(153, 153, 153));
        buttonLibroMostrar.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        buttonLibroMostrar.setForeground(new java.awt.Color(0, 51, 255));
        buttonLibroMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Menu/iconBuscarLibro.png"))); // NOI18N
        buttonLibroMostrar.setText("Mostrar");
        buttonLibroMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLibroMostrarActionPerformed(evt);
            }
        });
        itemAdminLibro.add(buttonLibroMostrar);

        jMenuBar3.add(itemAdminLibro);

        itemEmpleado.setForeground(new java.awt.Color(255, 255, 204));
        itemEmpleado.setText("Empleado");
        itemEmpleado.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N

        jMenuItem8.setBackground(new java.awt.Color(153, 153, 153));
        jMenuItem8.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jMenuItem8.setForeground(new java.awt.Color(255, 204, 0));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Menu/iconaltauser.png"))); // NOI18N
        jMenuItem8.setText("Alta");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        itemEmpleado.add(jMenuItem8);

        jMenuItem9.setBackground(new java.awt.Color(153, 153, 153));
        jMenuItem9.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jMenuItem9.setForeground(new java.awt.Color(255, 204, 0));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Menu/iconmodicaruser.png"))); // NOI18N
        jMenuItem9.setText("Modficar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        itemEmpleado.add(jMenuItem9);

        jMenuItem10.setBackground(new java.awt.Color(153, 153, 153));
        jMenuItem10.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jMenuItem10.setForeground(new java.awt.Color(255, 204, 0));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Menu/iconborraruser.png"))); // NOI18N
        jMenuItem10.setText("Baja");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        itemEmpleado.add(jMenuItem10);

        jMenuItem11.setBackground(new java.awt.Color(153, 153, 153));
        jMenuItem11.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jMenuItem11.setForeground(new java.awt.Color(255, 204, 0));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Menu/iconbuscaruser.png"))); // NOI18N
        jMenuItem11.setText("Mostrar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        itemEmpleado.add(jMenuItem11);

        jMenuBar3.add(itemEmpleado);

        itemInformacion.setForeground(new java.awt.Color(255, 255, 204));
        itemInformacion.setText("Informacion");
        itemInformacion.setToolTipText("");
        itemInformacion.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jMenuBar3.add(itemInformacion);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiquetaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(etiquetaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(etiquetaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(etiquetaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiquetaUsuario)
                .addGap(18, 18, 18)
                .addComponent(etiquetaNombre)
                .addGap(18, 18, 18)
                .addComponent(etiquetaApellido)
                .addGap(18, 18, 18)
                .addComponent(etiquetaFecha)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCompraAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCompraAlquilerActionPerformed
        new ClienteLibros(this, true).setVisible(true);
    }//GEN-LAST:event_itemCompraAlquilerActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
       new EmpleadoABM(this, true, this.user.getIdUsuario(),EABM.Alta).setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
       EmpleadoABM e=  new EmpleadoABM(this, true, this.user.getIdUsuario(),EABM.Baja);
       
       if(e.isShow()){
           e.setVisible(true);
       }
       
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
           EmpleadoABM e=  new EmpleadoABM(this, true, this.user.getIdUsuario(),EABM.Modificacion);
       
       if(e.isShow()){
           e.setVisible(true);
       }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
       new EmpleadoMostrar(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void buttonLibroAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLibroAltaActionPerformed
        new LibroABM(this,true, EABM.Alta, this.user.getIdUsuario()).setVisible(true);
    }//GEN-LAST:event_buttonLibroAltaActionPerformed

    private void buttonLibroModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLibroModificarActionPerformed
      LibroABM libro= new LibroABM(this,true,EABM.Modificacion,this.user.getIdUsuario());
      
      if(libro.isEstado()){
          libro.setVisible(true);
      }
    }//GEN-LAST:event_buttonLibroModificarActionPerformed

    private void buttonLibroBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLibroBajaActionPerformed
       LibroABM libro= new LibroABM(this,true,EABM.Baja,this.user.getIdUsuario());
      
      if(libro.isEstado()){
          libro.setVisible(true);
      }
    }//GEN-LAST:event_buttonLibroBajaActionPerformed

    private void buttonLibroMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLibroMostrarActionPerformed
     new LibrosMostrar(this, true).setVisible(true);
    }//GEN-LAST:event_buttonLibroMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem buttonLibroAlta;
    private javax.swing.JMenuItem buttonLibroBaja;
    private javax.swing.JMenuItem buttonLibroModificar;
    private javax.swing.JMenuItem buttonLibroMostrar;
    private javax.swing.JLabel etiquetaApellido;
    private javax.swing.JLabel etiquetaFecha;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JMenu itemAdminLibro;
    private javax.swing.JMenu itemCliente;
    private javax.swing.JMenuItem itemCompraAlquiler;
    private javax.swing.JMenu itemEmpleado;
    private javax.swing.JMenu itemInformacion;
    private javax.swing.JMenu itemLibro;
    private javax.swing.JMenuItem itemMisLibros;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    // End of variables declaration//GEN-END:variables
}
