/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fefe;
import java.awt.BorderLayout;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
/**
 *
 * @author Usuario
 */
public class rpg extends javax.swing.JFrame {
    private int ganadas =0;
   private int perdidas =0;
    private int empatadas = 0;
    private String radio ;
   private  String maquina;
ImageIcon imagenFondo = new ImageIcon(getClass().getResource("/imagen/racing3.jpg"));
    /**
     * Creates new form rpg
     */
    public rpg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        piedra = new javax.swing.JRadioButton();
        papel = new javax.swing.JRadioButton();
        tijera = new javax.swing.JRadioButton();
        aceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        racing = new javax.swing.JTextField();
        compu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        eGanadas = new javax.swing.JLabel();
        eEmpates = new javax.swing.JLabel();
        ePerdidas = new javax.swing.JLabel();
        versus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Piedra,Papel,Tijera");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        buttonGroup1.add(piedra);
        piedra.setFont(new java.awt.Font("X-Files", 0, 11)); // NOI18N
        piedra.setText("Piedra");

        buttonGroup1.add(papel);
        papel.setFont(new java.awt.Font("X-Files", 0, 11)); // NOI18N
        papel.setText("Papel");
        papel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papelActionPerformed(evt);
            }
        });

        buttonGroup1.add(tijera);
        tijera.setFont(new java.awt.Font("X-Files", 0, 11)); // NOI18N
        tijera.setText("Tijera");

        aceptar.setFont(new java.awt.Font("Palatino Linotype", 0, 11)); // NOI18N
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Year supply of fairy cakes", 1, 11)); // NOI18N
        jLabel1.setText("Eleji :");

        racing.setText("...");
        racing.setEnabled(false);
        racing.setFocusable(false);
        racing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                racingActionPerformed(evt);
            }
        });

        compu.setText("...");
        compu.setEnabled(false);
        compu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("X-Files", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("Pc :");

        eGanadas.setForeground(new java.awt.Color(51, 255, 255));
        eGanadas.setText("Ganadas:");

        eEmpates.setForeground(new java.awt.Color(255, 255, 255));
        eEmpates.setText("Empates:");

        ePerdidas.setForeground(new java.awt.Color(51, 255, 255));
        ePerdidas.setText("Perdidas");

        versus.setEnabled(false);
        versus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                versusActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("X-Files", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 190));
        jLabel3.setText("Piedra , Papel , Tijera");

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tijera)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(piedra, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(143, 143, 143))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(papel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(compu, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(aceptar)
                                .addGap(26, 26, 26)
                                .addComponent(refresh)
                                .addGap(18, 18, 18)
                                .addComponent(limpiar)))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(racing, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(versus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(eGanadas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eEmpates)
                                .addGap(89, 89, 89)))
                        .addComponent(ePerdidas)
                        .addGap(37, 37, 37)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(piedra)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(papel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tijera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(versus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(refresh)
                    .addComponent(limpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(racing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eGanadas)
                    .addComponent(eEmpates)
                    .addComponent(ePerdidas))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String  radio  (){
        try {
            if(buttonGroup1.isSelected(piedra.getModel())){
                return "Piedra";
            }else if(buttonGroup1.isSelected(papel.getModel())){
                return "Papel";
            }else if(buttonGroup1.isSelected(tijera.getModel())){
                return "Tijera";
            }
        } catch (Exception e) {
            return "nada" + e;
        }return "nada";
    }
    public  String maquina (){
        Random  random  = new Random ();
        String [] pc  = {"Piedra","Papel","Tijera"};
        int   num = random.nextInt(3);
        return pc[num];
    }
    public String  Total  (){
          this.radio = radio ();
          this.maquina = maquina ();
     if(radio == maquina ){
        compu.setText(maquina);
        empatadas+=1;
        return "Empate";
    }else if((radio == "Tijera")&& (maquina == "Papel")){
        compu.setText(maquina);
        ganadas+=1;
        return "Ganaste";
    }else if ((radio == "Papel")&&(maquina == "Piedra")){
        compu.setText(maquina);
        ganadas+=1;
        return "Ganaste";
    }else if ((radio =="Piedra")&& (maquina == "Tijera")){
        compu.setText(maquina);
        ganadas+=1;
        return "Ganaste";
    }else ;
      compu.setText(maquina);
      perdidas+=1;
      return "Perdiste";
    
    }
    private void papelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_papelActionPerformed

    private void racingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_racingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_racingActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        racing.setText(Total());
        versus.setText(radio +" Vs "+maquina);
         eEmpates.setText("Empates:" + empatadas);
     eGanadas.setText("Ganadas:"+ ganadas);
     ePerdidas.setText("Perididas:"+ perdidas);
    }//GEN-LAST:event_aceptarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       setIconImage(new ImageIcon(getClass().getResource("/imagen/images.jpg")).getImage());
        JLabel fondo = new JLabel();
        fondo.setIcon(imagenFondo);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, imagenFondo.getIconWidth(), imagenFondo.getIconHeight());
        this.add(fondo, BorderLayout.CENTER);
        fondo.setSize(400,400);
        this.setSize(375, 355);
        //this.setSize(fondo.getWidth(), fondo.getHeight());
        this.setLocationRelativeTo(null);
        
        
        eEmpates.setText("Empates:" + empatadas);
     eGanadas.setText("Ganadas:"+ ganadas);
     ePerdidas.setText("Perididas:"+ perdidas);
    }//GEN-LAST:event_formWindowOpened

    private void versusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_versusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_versusActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        versus.setText("");
        compu.setText("");
        racing.setText("");
    }//GEN-LAST:event_refreshActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
     versus.setText("");
        compu.setText("");
        racing.setText("");
        empatadas =0;
        ganadas =0;
        perdidas =0;
           eEmpates.setText("Empates:" + empatadas);
     eGanadas.setText("Ganadas:"+ ganadas);
     ePerdidas.setText("Perididas:"+ perdidas);
    }//GEN-LAST:event_limpiarActionPerformed

    private void compuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rpg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JTextField compu;
    private javax.swing.JLabel eEmpates;
    private javax.swing.JLabel eGanadas;
    private javax.swing.JLabel ePerdidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton limpiar;
    private javax.swing.JRadioButton papel;
    private javax.swing.JRadioButton piedra;
    private javax.swing.JTextField racing;
    private javax.swing.JButton refresh;
    private javax.swing.JRadioButton tijera;
    private javax.swing.JTextField versus;
    // End of variables declaration//GEN-END:variables
}
